# Generated by Django 2.2.2 on 2019-12-01 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191201_0922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usr',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userfollowers',
            old_name='usr',
            new_name='user',
        ),
    ]
