# Generated by Django 2.2.2 on 2019-12-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191201_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowers',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
