# Generated by Django 2.2.2 on 2019-12-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191202_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowers',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
