# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(801, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.verticalLayout_2.addWidget(self.doubleSpinBox)
        self.dateEdit = QtGui.QDateEdit(self.centralwidget)
        self.dateEdit.setObjectName(_fromUtf8("dateEdit"))
        self.verticalLayout_2.addWidget(self.dateEdit)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout.addWidget(self.toolButton, 4, 0, 1, 1)
        self.vb_one = QtGui.QVBoxLayout()
        self.vb_one.setObjectName(_fromUtf8("vb_one"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.vb_one.addWidget(self.pushButton_2)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setToolTip(_fromUtf8(""))
        self.pushButton.setStyleSheet(_fromUtf8("background-color:lightgreen; color:black;"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.vb_one.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.vb_one, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 801, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("creep-003.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuFile.setIcon(icon)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuFind = QtGui.QMenu(self.menuFile)
        self.menuFind.setObjectName(_fromUtf8("menuFind"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setAutoFillBackground(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("creep-002.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuEdit.setIcon(icon1)
        self.menuEdit.setSeparatorsCollapsible(False)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.menubar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("creep-001.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuView.setIcon(icon2)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionG = QtGui.QAction(MainWindow)
        self.actionG.setObjectName(_fromUtf8("actionG"))
        self.actionEdit = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("Text.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon3)
        self.actionEdit.setObjectName(_fromUtf8("actionEdit"))
        self.actionOpen = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("OK.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon4)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("Save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon5)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionDocument = QtGui.QAction(MainWindow)
        self.actionDocument.setObjectName(_fromUtf8("actionDocument"))
        self.actionImage = QtGui.QAction(MainWindow)
        self.actionImage.setObjectName(_fromUtf8("actionImage"))
        self.actionVideo = QtGui.QAction(MainWindow)
        self.actionVideo.setObjectName(_fromUtf8("actionVideo"))
        self.actionPdf = QtGui.QAction(MainWindow)
        self.actionPdf.setObjectName(_fromUtf8("actionPdf"))
        self.actionTextfile = QtGui.QAction(MainWindow)
        self.actionTextfile.setObjectName(_fromUtf8("actionTextfile"))
        self.actionReplace = QtGui.QAction(MainWindow)
        self.actionReplace.setObjectName(_fromUtf8("actionReplace"))
        self.actionUndo = QtGui.QAction(MainWindow)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionRedo = QtGui.QAction(MainWindow)
        self.actionRedo.setObjectName(_fromUtf8("actionRedo"))
        self.menuFind.addAction(self.actionDocument)
        self.menuFind.addAction(self.actionImage)
        self.menuFind.addAction(self.actionVideo)
        self.menuFind.addAction(self.actionPdf)
        self.menuFind.addAction(self.actionTextfile)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addAction(self.menuFind.menuAction())
        self.menuEdit.addAction(self.actionReplace)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.pushButton_2.setStatusTip(_translate("MainWindow", "i am the amount button", None))
        self.pushButton_2.setText(_translate("MainWindow", "amount button", None))
        self.pushButton.setStatusTip(_translate("MainWindow", " i am the date button", None))
        self.pushButton.setText(_translate("MainWindow", "Date Button", None))
        self.menuFile.setToolTip(_translate("MainWindow", "file", None))
        self.menuFile.setStatusTip(_translate("MainWindow", "file", None))
        self.menuFile.setTitle(_translate("MainWindow", "file", None))
        self.menuFind.setTitle(_translate("MainWindow", "find", None))
        self.menuEdit.setTitle(_translate("MainWindow", "edit", None))
        self.menuView.setTitle(_translate("MainWindow", "view", None))
        self.actionG.setText(_translate("MainWindow", "g", None))
        self.actionEdit.setText(_translate("MainWindow", "edit", None))
        self.actionOpen.setText(_translate("MainWindow", "open", None))
        self.actionSave.setText(_translate("MainWindow", "save", None))
        self.actionSave_as.setText(_translate("MainWindow", "save as", None))
        self.actionDocument.setText(_translate("MainWindow", "document", None))
        self.actionImage.setText(_translate("MainWindow", "image", None))
        self.actionVideo.setText(_translate("MainWindow", "video", None))
        self.actionPdf.setText(_translate("MainWindow", "pdf", None))
        self.actionTextfile.setText(_translate("MainWindow", "textfile", None))
        self.actionReplace.setText(_translate("MainWindow", "replace", None))
        self.actionUndo.setText(_translate("MainWindow", "undo", None))
        self.actionRedo.setText(_translate("MainWindow", "redo", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

