# Generated by Django 2.2.2 on 2019-09-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcloud', '0006_auto_20190827_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
