# Generated by Django 2.2.2 on 2019-09-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redcloud', '0008_auto_20190906_0325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='img',
            new_name='post_image',
        ),
    ]
