# Generated by Django 2.2.2 on 2019-09-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcloud', '0009_auto_20190906_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
