# Generated by Django 2.2.2 on 2019-11-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redcloud', '0013_auto_20191102_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_post',
        ),
    ]
