# Generated by Django 2.2.2 on 2019-11-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcloud', '0014_remove_post_image_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null='True', upload_to='post_pics'),
            preserve_default='True',
        ),
    ]
