# Generated by Django 2.2.2 on 2019-11-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redcloud', '0016_auto_20191102_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='posted_file'),
        ),
    ]
