# Generated by Django 2.2.2 on 2019-11-03 13:46

from django.db import migrations, models
import redcloud.validators


class Migration(migrations.Migration):

    dependencies = [
        ('redcloud', '0018_auto_20191103_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_pics', validators=[redcloud.validators.image_validator]),
        ),
    ]
